apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: qbittorrent-tls
  commonName: qbittorrent.homelab.com
  dnsNames:
    - qbittorrent.homelab.com
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
