apiVersion: v1
kind: Service
metadata:
  name: jellyfin-nodeport
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/service: jellyfin-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
      nodePort: 32096
