app-template:
  fullnameOverride: qbittorrent
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/qbittorrent
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: WEBUI_PORT
            value: '8084'
          - name: TORRENTING_PORT
            value: '6881'
          ports:
          - name: web
            containerPort: 8084
            hostPort: 8084
          - name: torrent-tcp
            containerPort: 6881
            protocol: TCP
            hostPort: 6881
          - name: torrent-udp
            containerPort: 6881
            protocol: UDP
            hostPort: 6881
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        web:
          enabled: true
          primary: true
          port: 8084
          protocol: HTTP
        torrent-tcp:
          enabled: true
          primary: false
          port: 6881
          protocol: TCP
        torrent-udp:
          enabled: true
          primary: false
          port: 6881
          protocol: UDP
        http:
          enabled: false
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: qbittorrent.home.local
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: web
  persistence:
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/qbittorrent"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-downloads:
      enabled: true
      type: hostPath
      hostPath: "/mnt/media"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/downloads"
