apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: central-secrets
  target:
    name: immich-db
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: immich-db
        property: POSTGRES_PASSWORD

