apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: audiobookshelf-tls
  commonName: audiobookshelf.homelab.com
  dnsNames:
    - audiobookshelf.homelab.com
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
