apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beszel
  namespace: {{ .Release.Namespace }}
spec:
  secretName: beszel-tls
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - beszel.homelab.com
