app-template:
  fullnameOverride: audiobookshelf
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/advplyr/audiobookshelf
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          ports:
          - name: http
            containerPort: 80
  service:
    main:
      enabled: true
      controller: main
      type: NodePort
      ports:
        http:
          enabled: true
          primary: true
          port: 80
          nodePort: 32378
          protocol: HTTP

  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: audiobook.home.arpa
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    main-library:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd2/audiobook"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/library"
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/audiobookshelf/config"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-metadata:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/audiobookshelf/metadata"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/metadata"
