apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: sonarr-tls
  commonName: sonarr.homelab.com
  dnsNames:
    - sonarr.homelab.com
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
