apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: copyparty-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: central-secrets
  target:
    name: copyparty-config
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: copyparty-config
