apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: filebrowser-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: central-secrets
  target:
    name: filebrowser-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: filebrowser-admin
        property: password
