apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: filebrowser-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: central-secrets
  target:
    name: filebrowser-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            port: 80
            cacheDir: /tmp/filebrowser-cache
            sources:
              - path: /media
                name: Media
                config:
                  defaultEnabled: true
              - path: /media/downloads
                name: Downloads
                config:
                  defaultEnabled: true
              - path: /media/books
                name: Books
                config:
                  defaultEnabled: true
              - path: /media/books/audiobookshelf
                name: Audiobookshelf Library
                config:
                  defaultEnabled: true
              - path: /media/books/calibre-library
                name: Calibre Library
                config:
                  defaultEnabled: true
              - path: /media/books/calibre-ingest
                name: CWA Book Ingest
                config:
                  defaultEnabled: true

          auth:
            adminUsername: admin
            adminPassword: "{{ `{{ .password }}` }}"
            methods:
              password:
                enabled: true
                minLength: 10

          frontend:
            name: Homelab Files
  data:
    - secretKey: password
      remoteRef:
        key: filebrowser-admin
        property: password
