app-template:
  fullnameOverride: copyparty
  controllers:
    main:
      containers:
        main:
          image:
            repository: copyparty/ac
            tag: latest
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: copyparty-config
                  key: password
          args:
            - "-a"
            - "admin:$(PASSWORD)"
            - "-v"
            - "/w:/:rw,admin"
            - --rproxy=-1
            - --xff-src=10.42.0.0/16
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/"
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 60
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: "/"
                  port: http
                initialDelaySeconds: 15
                periodSeconds: 60
            startup:
              enabled: false
          ports:
          - name: http
            containerPort: 3923
      pod:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 3923
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      tls:
        - hosts:
            - share.home.arpa
          secretName: copyparty-tls
      hosts:
      - host: share.home.arpa
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:

    main-share:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd2"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/w"
