app-template:
  fullnameOverride: jellyfin
  controllers:
    main:
      containers:
        main:
          image:
            repository: jellyfin/jellyfin
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          resources:
            limits:
              memory: 1Gi
          ports:
          - name: http
            containerPort: 8096
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8096
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: jellyfin.home.local
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/jellyfin/config"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-cache:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/jellyfin/cache"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/cache"
    main-media:
      enabled: true
      type: hostPath
      hostPath: "/mnt/media"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/media"
            readOnly: true
