app-template:
  fullnameOverride: uptime-kuma
  controllers:
    main:
      pod:
        nodeSelector:
          node-type: infra
      containers:
        main:
          image:
            repository: louislam/uptime-kuma
            tag: latest
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 3001
                initialDelaySeconds: 30
                periodSeconds: 10
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /
                  port: 3001
                initialDelaySeconds: 10
                periodSeconds: 10
            startup:
              enabled: false
          ports:
          - name: web
            containerPort: 3001
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        web:
          enabled: true
          primary: true
          port: 3001
          protocol: HTTP
        http:
          enabled: false
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      tls:
        - hosts:
            - uptime.homelab.com
          secretName: uptime-kuma-tls
      hosts:
      - host: uptime.homelab.com
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: web
  persistence:
    main-config:
      enabled: true
      type: persistentVolumeClaim
      storageClass: longhorn
      size: 2Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
          - path: "/app/data"
