app-template:
  fullnameOverride: radarr
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: TZ
            value: Asia/Ho_Chi_Minh
          ports:
          - name: web
            containerPort: 7878
            hostPort: 7878
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        web:
          enabled: true
          primary: true
          port: 7878
          protocol: HTTP
        http:
          enabled: false
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: radarr.home.arpa
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: web
  persistence:
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/infra-data/radarr"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-media:
      enabled: true
      type: hostPath
      hostPath: "/mnt/media"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/data"
