apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: olivetin
  namespace: {{ .Release.Namespace }}
spec:
  secretName: olivetin-tls
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - power.homelab.com
