apiVersion: v1
kind: ServiceAccount
metadata:
  name: stack-configurator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stack-configurator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stack-configurator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stack-configurator
subjects:
  - kind: ServiceAccount
    name: stack-configurator
    namespace: {{ .Release.Namespace }}
