traefik:
  fullnameOverride: traefik
  nodeSelector:
    node-type: infra
  deployment:
    replicas: 1
  ingressClass:
    name: traefik
    enabled: true
    isDefaultClass: true
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      ingressEndpoint:
        hostname: traefik.home.arpa
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      http:
        tls:
          enabled: true
  service:
    spec:
      type: LoadBalancer
  logs:
    general:
      level: INFO
