app-template:
  fullnameOverride: filebrowser
  controllers:
    main:
      containers:
        main:
          image:
            repository: gtstef/filebrowser
            tag: stable
          env:
          - name: FILEBROWSER_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: filebrowser-admin
                key: password
          ports:
          - name: http
            containerPort: 80
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: homelab-ca
      tls:
        - hosts:
            - filebrowser.homelab.com
          secretName: filebrowser-tls
      hosts:
      - host: filebrowser.homelab.com
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    media-share:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: media-share
      advancedMounts:
        main:
          main:
          - path: "/media"
    config:
      enabled: true
      type: configMap
      name: filebrowser-config
      advancedMounts:
        main:
          main:
          - path: "/home/filebrowser/data/config.yaml"
            subPath: config.yaml
    data:
      enabled: true
      type: persistentVolumeClaim
      storageClass: longhorn
      size: 1Gi
      accessMode: ReadWriteOnce
      advancedMounts:
        main:
          main:
          - path: "/home/filebrowser/data/tmp"
            subPath: tmp
