apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/huynhtt8/homelab.git
    targetRevision: main
    path: infra/central-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: central-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

