apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: calibre-web-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: calibre-web-tls
  commonName: library.home.arpa
  dnsNames:
    - library.home.arpa
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
